default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: Weka_development

test:
  <<: *default
  database: Weka_test

production:
  <<: *default
  database: Weka_production
